//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_BĐS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOUTU
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public string Image { get; set; }
        public Nullable<int> User_Update { get; set; }
    }
}
